### ISSUE TITLE
Treatment-specific mean estimation?

### ISSUE THREAD

**Issue by ck37** [Larsvanderlaan/causalGLM-depreciated-#1]
Hi Lars,

Looks like a very cool package - well done on getting this working.

One Q: do you have any interest, or is it already possible, to estimate treatment-specific means with this package? When analyzing surveys we often want to estimate a E[Y | A = 1] where A corresponds to survey response, rather than a contrast-oriented parameter like ATE/OR/RR. A TSM is naturally a component of these other parameters of course.

Cheers,
Chris

**Comment by Larsvanderlaan** [comment]
Hi Chris,

Thank you for reaching out. The R GitHub package tlverse/tmle3 does support nonparametric estimation of the marginal TSM E[Y|A=1] if that is of interest. I can provide some code using tmle3 if you would like. The causalGLM package is primarily focused on conditional parameters where the contrasts are modeled parametrically and nuisances nonparametrically (or nonparametric working model extensions of this). I can definitely add user-friendly versions of TSM to this package as well, although in the future the plan is to have this package fall under the tlverse and tmle3 framework as well. Alternatively, you could use this function: [Threshold_PointTreatment.R](https://github.com/Larsvanderlaan/ThresholdTMLE/blob/master/R/Threshold_PointTreatment.R)
, which is related to a different project and not as user-friendly. It technically estimates the threshold mean function E_W E[Y|A>=v,W] where v is a threshold and A is continuous. If A is binary, it stills works and you can set v=1 to estimate E_W E[Y|A=1,W]. To estimate E_W E[Y|A=0,W], you can do a similar trick with -1*A. It also supports weighting/biased sampling if that is useful.
 
Was this the kind of thing you had in mind?


 [tmle3](https://github.com/tlverse/tmle3/blob/master/R/Param_TSM.R)

**Comment by ck37** [comment]
Hi Lars,

Thanks for this detailed response, that makes complete sense. I will go ahead and close this issue (and saw the new repo anyway).

Appreciate it,
Chris

**Comment by Larsvanderlaan** [comment]
Hi Chris, Yes, the new repo should now implement the TSM and even allows for marginal structural versions of the TSM if that is of interest. (The new repo will actually move to github/tlverse in a short while).I did a few simulations and it looks like it works but I am still debugging/adding features so everything is in flux at the moment.Best,Lars
    On Tuesday, September 7, 2021, 12:45:53 PM PDT, Chris Kennedy ***@***.***> wrote:  
 
 


Hi Lars,

Thanks for this detailed response, that makes complete sense. I will go ahead and close this issue (and saw the new repo anyway).

Appreciate it,
Chris

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
